# Generated by Django 5.1.5 on 2026-02-10 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em Andamento'), ('WAITING_USER', 'Aguardando Usuário'), ('RESOLVED', 'Resolvido'), ('CANCELED', 'Cancelado')], db_index=True, default='OPEN', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='MEDIUM', max_length=20, verbose_name='prioridade')),
                ('category', models.CharField(choices=[('GENERAL', 'Geral'), ('TECHNICAL', 'Técnico'), ('BILLING', 'Financeiro'), ('ACCESS', 'Acesso'), ('BUG', 'Bug / Erro'), ('FEATURE', 'Solicitação de Feature'), ('OTHER', 'Outro')], db_index=True, default='GENERAL', max_length=20, verbose_name='categoria')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='atribuído a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Chamado Criado'), ('STATUS_CHANGED', 'Status Alterado'), ('ASSIGNED', 'Responsável Atribuído'), ('UNASSIGNED', 'Responsável Removido'), ('PRIORITY_CHANGED', 'Prioridade Alterada'), ('CANCELED', 'Chamado Cancelado'), ('RESOLVED', 'Chamado Resolvido'), ('REOPENED', 'Chamado Reaberto'), ('MESSAGE_ADDED', 'Mensagem Adicionada')], db_index=True, max_length=30, verbose_name='tipo do evento')),
                ('from_value', models.CharField(blank=True, default='', max_length=255, verbose_name='valor anterior')),
                ('to_value', models.CharField(blank=True, default='', max_length=255, verbose_name='novo valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket', verbose_name='chamado')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_events_triggered', to=settings.AUTH_USER_MODEL, verbose_name='disparado por')),
            ],
            options={
                'verbose_name': 'Evento do Chamado',
                'verbose_name_plural': 'Eventos dos Chamados',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='mensagem')),
                ('is_internal', models.BooleanField(default=False, help_text='Visível apenas para moderadores e admins.', verbose_name='mensagem interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket', verbose_name='chamado')),
            ],
            options={
                'verbose_name': 'Mensagem do Chamado',
                'verbose_name_plural': 'Mensagens dos Chamados',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='idx_ticket_status_created'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_ticket_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', 'status'], name='idx_ticket_owner_status'),
        ),
    ]
